// <auto-generated />
using ApiForProject;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ApiForProject.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ApiForProject.Entities.Activity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Activities");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Description = "Примерьте странные наряды, зайдите в ту самую сувенирную лавочку, купите попкорн и съешьте его на диванчиках.",
                            ImageUrl = "https://i.ibb.co/wwjG5vx/image.webp",
                            Title = "Торговый центр"
                        },
                        new
                        {
                            Id = 2L,
                            Description = "Это такой мастер-класс, где участники рисуют изображение под руководством художника. Микс обучения и элементов творчества. А еще у вас останутся готовые картины, которыми можно обменяться в конце.",
                            ImageUrl = "https://i.ibb.co/0swd2bL/image.webp",
                            Title = "Арт-вечеринки"
                        },
                        new
                        {
                            Id = 3L,
                            Description = "Сходите вместе на квест, это подарит вам кучу незабываемых эмоций. Квесты можно подобрать под любое настроение.",
                            ImageUrl = "https://i.ibb.co/YR6RPZg/image.webp",
                            Title = "Квесты"
                        },
                        new
                        {
                            Id = 4L,
                            Description = "Это такой мастер-класс, где участники готовят под руководством поваров, поэтому голодными вы точно не останетесь.",
                            ImageUrl = "https://i.ibb.co/djMcRh7/image.webp",
                            Title = "Кулинарный мастер-класс"
                        },
                        new
                        {
                            Id = 5L,
                            Description = "В переходах, на улице или в амфитеатрах — такие выступления обладают особой атмосферой, которая добавляет свиданиям романтики.",
                            ImageUrl = "https://i.ibb.co/bvt6F97/image.jpg",
                            Title = "Живая музыка"
                        },
                        new
                        {
                            Id = 6L,
                            Description = "Романтический вечер и полный релакс. И пусть весь мир подождет!",
                            ImageUrl = "https://i.ibb.co/BZqfpWT/image.jpg",
                            Title = "СПА для двоих"
                        },
                        new
                        {
                            Id = 7L,
                            Description = "Для тех кто любит животных.",
                            ImageUrl = "https://i.ibb.co/0BQ44NC/image.webp",
                            Title = "Посетите зоопарк"
                        },
                        new
                        {
                            Id = 8L,
                            Description = "Неустаревающая классика. Но свиданию может помешать плохая погода.",
                            ImageUrl = "https://i.ibb.co/BnRKWfM/image.webp",
                            Title = "Пикник на крыше"
                        },
                        new
                        {
                            Id = 9L,
                            Description = "Без стеснения пойте любимые песни.",
                            ImageUrl = "https://i.ibb.co/5KpzG7L/image.webp",
                            Title = "Вечер караоке"
                        },
                        new
                        {
                            Id = 10L,
                            Description = "В том, чтобы выбрать партнеру одежду, действительно есть что-то трогательное. Важно вдумчиво и внимательно подойти к процессу и, конечно, повеселиться.",
                            ImageUrl = "https://i.ibb.co/ZXFZvwM/image.webp",
                            Title = "Покупайте новые наряды"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
